web:
  build: .
  command: 'bash -c ''heroku-with-docker'''
  working_dir: /app/user/src/github.com/kwmt/heroku-with-docker
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user/src/github.com/kwmt/heroku-with-docker
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user/src/github.com/kwmt/heroku-with-docker'
